version: '3.1'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: theSkinBeauty-mysql
    ports:
      - '3306:3306'
    restart: always
    env_file:
      - ../config/.server.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ=Australia/Sydney
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/docker/data/mysql:/var/lib/mysql

  nodejs:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: dockerfile
    image: skinbeauty-nodejs-image
    container_name: skinbeauty-nodejs-container
    ports:
      - '5100:5100'
    env_file:
      - ../config/.server.env
    restart: always
